const vinoteca = {
    "vinos":[
      {
      "id": 1,
      "image":"1.jpg",
      "name": "Familia Blanco Blend",
      "state":"En stock",
      "bodega":"Familia Blanco",
      "region": "Ugarteche (Luján de Cuyo). Mendoza.",
      "crianza": "15 meses en roble Francés",
      "graduacion": "14,0%",
      "cepa": "Blend",
      "description": "Malbec, Bonarda y Cabernet Sauvignon sellados con una sutil presencia de Cabernet Franc dan vida a un blend de excelencia. Refinado, distinguido y complejo.",
      "category":"Vinos tintos",
      "price": 11800
    },
    {
      "id": 2,
      "image":"2.jpg",
      "name": "Bo Bó Bohemian Zorrito Mb",
      "state":"En stock",
      "bodega":"Bo-Bó Wines",
      "region": "Alto Agrelo (Luján de Cuyo). Mendoza.",
      "crianza": "6 meses en barricas de roble americano de tercer uso",
      "graduacion": "14,9%",
      "cepa": "Malbec",
      "description": "Un Malbec fresco, rústico, salvaje, indómito: vinificado con levaduras naturales , buscando reflejar lo mas puro del espíritu del Malbec de nuestro viñedo directo de la botella.",
      "category":"Vinos tintos",
      "price": 3800
    },
    {
      "id": 3,
      "image":"3.jpg",
      "name": "Piel Negra",
      "state":"En stock",
      "bodega":"Bressia",
      "region": "Valle de Uco; Mendoza.",
      "crianza": "24 meses en barricas nuevas de roble francés.",
      "graduacion": "14,5%",
      "cepa": "Pinot Noir",
      "description": "Este varietal 100% pinot noir sorprende por la tonalidad e intensidad en su aspecto visual ya que ofrece un color rojo profundo muy intenso con matices negros de gran atractivo y vivacidad.",
      "category": "Vinos tintos",
      "price": 8500
    },

      {
      "id": 4,
      "image":"4.jpg",
      "name": "Domiciano Mistela",
      "state":"En stock",
      "bodega":"Domiciano",
      "region": "Barrancas de Maipu, Mendoza",
      "crianza": "4 años en barricas de roble frances",
      "graduacion": "15,0%",
      "cepa": "Moscatel, Torrontés",
      "description": "Esta MISTELA DOMICIANO es elaborada a partir de una selección de uvas Moscatel y Torrontes. Una vez cortadas con alcohol vinico, son criadas por 4 años en barricas de roble frances para logra la complejidad aromatica y color caramelo que la caracterizan.",
      "category": "Vinos rosados",
      "price": 3750
    },
    {
      "id": 5,
      "image":"5.jpg",
      "name": "El Esteco Old Vines Criolla",
      "state":"En stock",
      "bodega":"El Esteco",
      "region": "Valle de Cafayate, Salta",
      "crianza": "Embotellado sin filtración previa y estiba durante 6 a 8 meses",
      "graduacion": "14,0%",
      "cepa": "Criolla",
      "description": "El Esteco Old Vines es un homenaje a la vida y trayectoria de algunas de nuestras fincas con más de 50 años de antigüedad. Viñedos que viven en armonía con el terroir y precisan la mínima intervención del hombre para regalarnos vinos excepcionales.",
      "category": "Vinos rosados",
      "price": 5850
    },
    {
      "id": 6,
      "image":"6.jpg",
      "name": "Angélica Zapata",
      "state":"Agotado",
      "bodega":"Catena Zapata",
      "region": "Gualtallary (Tupungato). Mendoza",
      "crianza": "14 meses en roble Francés (40% nuevo).",
      "graduacion": "13,9%",
      "cepa": "Chardonnay",
      "description": "Angélica Chardonnay es un “single vineyard” que refleja características propias de la zona de gran altitud en donde se origina. ",
      "category": "Vinos rosados",
      "price": 4320
    },

      {
      "id": 7,
      "image":"7.jpg",
      "name": "Verum",
      "state":"En stock",
      "bodega":"Del Rio Elorza",
      "region": "Fernandez Oro, Alto Valle Rio Negro, Patagonia.",
      "crianza": "5 % en roble francés de primer uso, 5% de roble americano de primer uso, 90 % en tanques de acero inoxidable (sobre borra)",
      "graduacion": "14,0%",
      "cepa": "Chardonnay",
      "description": "Un Chardonnay 100% bajo el estilo del mejor Borgoña",
      "category": "Vinos blancos",
      "price": 3700
    },
    {
      "id": 8,
      "image":"8.jpg",
      "name": "Fond de Cave Reserva Cha",
      "state":"En stock",
      "bodega":"Trapiche",
      "region": "Mendoza.",
      "crianza": "9 meses en barricas de roble frances y americano.",
      "graduacion": "13,5%",
      "cepa": "Chardonnay",
      "description": "Muy elegante, este vino despliega aromas a manzanas rojas, peras, miel y canela. De gran frescura, es untuoso y posee un carácter mineral. En boca presenta un suave final.",
      "category": "Vinos blancos",
      "price": 2650
    },
    {
      "id": 9,
      "image":"9.jpg",
      "name": "Marchiori & Barraud",
      "state":"En stock",
      "bodega":"Marchiori & Barraud",
      "region": "Perdriel (Luján de Cuyo). Mendoza.",
      "crianza": "7 meses sobre borras.",
      "graduacion": "14,1%",
      "cepa": "Chardonnay",
      "description": "Es un Chardonnay voluminoso y largo en su paso. Especial para acompañar carnes de aves de corral, con salsas a base de cremas y alcaparras",
      "category": "Vinos blancos",
      "price": 2500
    },

      {
        "id": 10,
        "image":"10.jpg",
        "name": "Moet & Chandon Imperial",
        "state":"Agotado",
        "bodega":"Moet & Chandon",
        "region": "Épernay. Champagne, Francia.",
        "crianza": "Envejecido en tanques durante 3 a 9 meses, 50% leñoso.",
        "graduacion": "12%",
        "cepa": "Brut",
        "description": "Moët & Chandon Impérial es el champán icónico de la Maison. Creado en 1869, encarna el estilo único de Moët & Chandon, un estilo que se distingue por su frutado brillante, su paladar seductor y su elegante madurez.",
        "category": "Vinos espumantes",
        "price": 33600
      },
      {
        "id": 11,
        "image":"11.jpg",
        "name": "Dom Pérignon Vintage 2009",
        "state":"En stock",
        "bodega":"Dom Pérignon",
        "region": "Hautvillers. Champagne, Francia.",
        "crianza": "Envejecido en tanques durante 3 a 9 meses, 50% leñoso.",
        "graduacion": "12,5%",
        "cepa": "Blend",
        "description": "Dom Pérignon Vintage se elabora exclusivamente a partir de las mejores uvas de un único año, reinventándose a sí mismo mediante la interpretación del singular carácter de las estaciones y atreviéndose a no elaborar un Vintage si la cosecha no cumple las elevadas expectativas.",
        "category": "Vinos espumantes",
        "price": 55000
      },
      {
        "id": 12,
        "image":"12.jpg",
        "name": "Veuve Clicquot Brut “Yellow Label”",
        "state": "En stock",
        "bodega":"Veuve Clicquot",
        "region": "Reims. Champagne, Francia.",
        "crianza": "Envejecido en tanques durante 3 a 9 meses, 50% leñoso.",
        "graduacion": "12,0%",
        "cepa": "Brut",
        "description": "Veuve Clicquot Yellow Label es un ejemplo perfecto de armonía entre delicadeza y energía. Dominada por Pinot Noir, este vino tiene una estructura firme, redondeada con un toque de Pinot Meunier.",
        "category": "Vinos espumantes",
        "price": 35500
      }
    ]
}
